### ISSUE TITLE
可以把 README 改成英语

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/bilingual_book_maker#28]
然后加个 README-CN 其它语言的朋友现在也可以用了

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by MIBlue119** [comment]
I try some settings to provide this ~

Sources:
1. An example to use multiple language README: https://github.com/jonatasemidio/multilanguage-readme-pattern
2. Multiple language badge render with shields.io: https://shields.io/ 
3. Automatically generate different language README.md  with Gihub action: https://github.com/dephraiim/translate-readme

Steps:
1. Generate the badges for README.md hyperlink
   - example
      - https://img.shields.io/badge/lang-zh--Hans-blue.svg 
      - https://img.shields.io/badge/lang-en-red.svg
2. Copy the github action to project's action yaml file
```
name: Translate README

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
```

3. Set the project's action settings to change the Workflow Permissions

![Screen Shot 2023-03-04 at 8 01 11 PM](https://user-images.githubusercontent.com/9137836/222900405-4002214e-6c29-4dbf-b68d-537c572855c8.jpg)
